<div class="container">
    <div class="col-md-12">
        <div class="row">
            <div class="col core-cont text-center rounded">
                <h1>Login / Registration</h1>
            </div>
        </div>
        <div class="row">
            <a class="link-unstyled" href="account/login">
                <div class="col core-cont loginbutton text-center h3 rounded">
                    Login
                </div>
            </a>
            <a class="link-unstyled" href="account/register">
                <div class="col core-cont registerbutton text-center h3 rounded">
                    Register
                </div>
            </a>
        </div>
    </div>
</div>