<div class="container">

    <div class="col-md-12">

        <div class="row mb-5">
            <div class="col core-cont text-center">
                <h1>Login / Registration</h1>
            </div>
        </div>

        <div class="row">
            <a class="link-unstyled" href="account/login">
                <div class="center logregbuts core-cont text-center h3">
                    Login
                </div>
            </a>
        </div>

        <div class="row">
            <a class="link-unstyled" href="account/register">
                <div class="center logregbuts core-cont text-center h3">
                    Register
                </div>
            </a>
        </div>

    </div>
</div>