<div class="container">
    <div class="col-md-12">
        <div class="core-cont text-center h1 rounded">
            <?= $local_title ?>
        </div>

        <div class="core-cont rounded pt-0">
            <div class="container text-center p-3">
                <?= $msg ?>
                <hr>
            </div>
            <div class="container">
                <div class="row">
                    <?php
                        $config = json_decode(file_get_contents("config.json"));
                        foreach($config->ADMIN_CONTROLLER->ADMIN_TOOLS as $item)
                        {
                            if ($_SESSION['USER']->clearance == "admin")
                            {
                                if ($item->security == "user" || $item->security == "admin" || $item->security == "all")
                                {
                                    echo '<a href="' . $item->link . '">
                                        <div class="portal-button bg-light">
                                            <i class="' . $item->icon . '"></i>
                                            <hr>
                                            ' . $item->text . '
                                        </div>
                                    </a>
                                    ';
                                }
                            }
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>