<div class="container">
    <div class="col-md-12">
        <div class="core-cont text-danger">
            <h2>Error</h2>
            <?php
                if (isset($errors))
                {
                    foreach($errors as $error)
                    {
                        echo "<p>" . $error . "</p>";
                    }
                }
            ?>
        </div>
    </div>
</div>
