<div class="container">
    <div class="col-md-12">
        <div class="core-cont text-center h1 rounded">
            Login
        </div>

        <div class="core-cont rounded pt-0">
            <div class="container text-center p-3">
                If you are having trouble with your account just dm me I'll sort it. - Jack
                <hr>
            </div>
            <div class="container">
                <form action="account/submitLogin" method="post">
                    <div class="row mb-3">
                        <div class="col text-right">
                            Username
                        </div>
                        <div class="col text-left">
                            <input type="text" name="USERNAME" minlength="4" maxlength="10" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col text-right">
                            Password
                        </div>
                        <div class="col text-left">
                            <input type="password" name="PASSWORD" minlength="8" required>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col text-right">
                        </div>
                        <div class="col text-left">
                            <input type="submit" value="Log In">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>