<div class="container">
    <div class="col-md-12">
        <div class="core-cont text-center h1 rounded">
            Register
        </div>

        <div class="core-cont rounded pt-0">
            <div class="container text-center p-3">
                Please fill out the details below and click submit, all fields are required.<hr>
            </div>
            <div class="container">
                <form action="account/submitRegistration" method="post">
                    <div class="row mb-3">
                        <div class="col text-right">
                            First Name
                        </div>
                        <div class="col text-left">
                            <input type="text" name="FIRST_NAME" minlength="2" maxlength="15" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col text-right">
                            Last Name
                        </div>
                        <div class="col text-left">
                            <input type="text" minlength="3" maxlength="15" name="LAST_NAME" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col text-right">
                            Username
                        </div>
                        <div class="col text-left">
                            <input type="text" name="USERNAME" minlength="4" maxlength="10" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col text-right">
                            Password
                        </div>
                        <div class="col text-left">
                            <input type="password" name="PASSWORD" minlength="8" required>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col text-right">
                        </div>
                        <div class="col text-left">
                            <input type="submit">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>